### ISSUE TITLE
Can we have the whole Paytm payment gateway UI

### ISSUE THREAD

**Issue by pendyalaharsha** [mrdishant/Paytm-All-in-one-flutter-sdk#1]
I mean earlier we were given options to pick the payment mode inside the Payment gateway UI. I found it very convenient is there any way where in we can start the payment without specifying the payment mode.

**Comment by mrdishant** [comment]
Just don't add the following in the request of Transaction Status API. (Server SIde)
"enablePaymentMode" : []
