### ISSUE TITLE
Patym Network error

### ISSUE THREAD

**Issue by MaheshPeri19** [mrdishant/Paytm-All-in-one-flutter-sdk#10]
I am getting network error for both staging and production. I think it is releted to paytm itself.

{errorMessage: networkError, error: true}

Any suggestions to solve this ?

**Comment by mrdishant** [comment]
Try Uninstalling PAYTM App if Staging

**Comment by MaheshPeri19** [comment]
Do you mean need to delete paytm app from my mobile and test ?

But for production also, same error is coming.

**Comment by bhaumik1991** [comment]
I am getting the same issue in production server.

**Comment by bhaumik1991** [comment]
> Try Uninstalling PAYTM App if Staging

I am getting the same issue {errorMessage: networkError, error: true} in production.
