### ISSUE TITLE
How to add QR Code Scan feature in my app ?

### ISSUE THREAD

**Issue by archit-aggarwal** [mrdishant/Paytm-All-in-one-flutter-sdk#13]

**Comment by Arshaque** [comment]
As we are implementing the PayTM payment gateway, why would we be interested in scanning QR codes? If we wanted to pay using QR codes, the PayTM app is enough. If we wanted to pay the bill within the application, we are already redirecting to the PayTM application with the recipient's address. and most of all, if we wanted to pay using a QR scanner, we need to use another device.
