### ISSUE TITLE
session expired due to inactivity ?

### ISSUE THREAD

**Issue by MaheshPeri19** [mrdishant/Paytm-All-in-one-flutter-sdk#16]
I am using lastest paytm version 2.0.0. I am getting below error after payment.

"OOPS. Something went wrong. it may due to any of these reasons. Session expired due to inactivity.."

Then it is not redirecting to my app again. In this case, payment is success and money is deducting. 

Please help me to solve this.

Edit : 

`It is working fine for Android. Above issue is with iOS.
`

**Comment by mrdishant** [comment]
<img width="849" alt="Screenshot 2021-01-18 at 11 48 34 AM" src="https://user-images.githubusercontent.com/25786428/104879044-1aca8580-5983-11eb-92a8-c2ddea0e985d.png">

Check URL scheme it must be paytm+"YOUR_ACCOUNT_MID"

**Comment by MaheshPeri19** [comment]
Yes. already added both step 1 and 2 above mentioned. I am getting exactly below error.

```
-canOpenURL: failed for URL: "paytm://merchantpayment?txnToken=<my_token>&orderId=<MyOrderId>&mid=<MyMID>&amount=1.30&redirectionUrl=https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=<MyOrderId>" 

- error: "The operation couldn’t be completed. (OSStatus error -10814.)"
```

`Callback url : https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=<MyOrderId>`

**Comment by mrdishant** [comment]
-canOpenURL: failed for URL: "paytm://merchantpayment?txnToken=<my_token>&orderId=<MyOrderId>&mid=<MyMID>&amount=1.30&redirectionUrl=https://securegw.paytm.in/theia/paytmCallback?ORDER_ID=<MyOrderId>" 

- error: "The operation couldn’t be completed. (OSStatus error -10814.)"

It Must be paytmMID://....

Can you share a screenshot of URL Types in iOS Configuration

**Comment by MaheshPeri19** [comment]
Pls find screenshots below 

<img width="638" alt="1" src="https://user-images.githubusercontent.com/58836654/104899101-6fc8c480-59a0-11eb-9ed9-3d86080a1577.png">

<img width="789" alt="2" src="https://user-images.githubusercontent.com/58836654/104899121-735c4b80-59a0-11eb-8b2e-9728a7e48acb.png">

**Comment by MaheshPeri19** [comment]
@mrdishant 

Paytm app is not installed and I ran this example sample app in my iPhone 11 with **Test credentials as well as production**. It is working fine. But in project, it is not working with production credentials. Money is deducting and not redirecting to app again due to session inactivity.
