### ISSUE TITLE
App stops  on running function  on android 11

### ISSUE THREAD

**Issue by gauravmehta13** [mrdishant/Paytm-All-in-one-flutter-sdk#19]

**Comment by imyogisingh** [comment]
Any resolution on this bug?

**Comment by wrteam02** [comment]
any solution ?
app crash on android version 11

**Comment by imyogisingh** [comment]
Just add these lines. 
[Paytm ](https://developer.paytm.com/docs/all-in-one-sdk/hybrid-apps/flutter/) 

![IMG_20211110_160559](https://user-images.githubusercontent.com/31235444/141097983-8020c1fb-f972-4a04-ae6f-b928024941a8.jpg)

**Comment by wrteam02** [comment]
@imyogisingh sir, thank u for your response..
solved that err by adding this line.. implementation ‘com.squareup.okhttp3:logging-interceptor:4.4.0’

**Comment by mrdishant** [comment]
Android SDK updated in plugin. Error fixed in the latest version
