### ISSUE TITLE
Why does it has to work with production credentials?

### ISSUE THREAD

**Issue by EffyCoder** [mrdishant/Paytm-All-in-one-flutter-sdk#2]
We won't get credentials unless do the testing.

**Comment by MaheshPeri19** [comment]
Yes. Better to have staging testing many times in all scenarios. Then only better to go with production. Please allow staging environment to test.

**Comment by mrdishant** [comment]
> We won't get credentials unless do the testing.

Hi EffyCoder

The thing is this plugin is coded on Paytm all in one SDK. Paytm all in one SDK does not support the Staging environment.
So you can not use the plugin with staging credentials.

**Comment by EffyCoder** [comment]
@mrdishant Ok thanks for clarification. But as per my information there is staging and production environment setup in All in onre SDK.
see at the end of the page there is setup.
https://developer.paytm.com/docs/all-in-one-sdk/sdk-based-integration/

**Comment by faisalmushtaq007** [comment]
@EffyCoder have you found any solution, as to how to move to production level. Paytm team is asking for atleast three transactions in the STAGING level. I'm stuck with this problem from days and i've a deadline. Please!!!

**Comment by EffyCoder** [comment]
@faisalmushtaq007 I had to build custom checkout to get the credentials with one of the payment methods.

**Comment by faisalmushtaq007** [comment]
Can you help me with that @EffyCoder

**Comment by mrdishant** [comment]
Closing the issue as the plugin updated and staging support added.
