### ISSUE TITLE
How to add Withdrawal feature into flutter app?

### ISSUE THREAD

**Issue by ycv005** [mrdishant/Paytm-All-in-one-flutter-sdk#21]
Within my app, I have a rewards program and referral as well. Now, I want user to take benefit of them, and earn rewards as coin which can further be redeemed as cash. But to redeem, a user needs to withdraw money to its account. How could I achieve this within my app?

**Comment by mrdishant** [comment]
Hi @ycv005 
I think this can not be done with this plugin. You need to look for any payout solution like Cashfree Payouts, RazorpayX etc.
