### ISSUE TITLE
Upi Apps not showing 

### ISSUE THREAD

**Issue by imyogisingh** [mrdishant/Paytm-All-in-one-flutter-sdk#23]
Sir in my phone all the upi apps are there but when we use mode 2 as UPI we don't get any option to choose the upi app for the payment instead we are asked to enter upi id manually. Pls check this out.

**Comment by mrdishant** [comment]
If you want to use only UPI Intent within All-in-One SDK, pass the below params:

"enablePaymentMode" : [{
    "mode":"UPI",
    "channels":["UPIPUSH"]
}]
