### ISSUE TITLE
Can you help me with STAGING level

### ISSUE THREAD

**Issue by faisalmushtaq007** [mrdishant/Paytm-All-in-one-flutter-sdk#5]
I've to first show three transactions in STAGING level, then after i'll get the production level key from the paytm team.
Please help!

**Comment by mrdishant** [comment]
Don't worry

The plugin will be updated within 3 days and you can try stagging then.

**Comment by faisalmushtaq007** [comment]
@mrdishant Are you sure??

**Comment by mrdishant** [comment]
yeah

**Comment by faisalmushtaq007** [comment]
@mrdishant Thanks alot

**Comment by faisalmushtaq007** [comment]
@mrdishant  Any luck with the stagging issue, i have to show the payment section to the client. Please help! PLEASE

**Comment by mrdishant** [comment]
I am on it.

For the time being, can you try the following app

https://github.com/paytm/Paytm_Payments_Android_Sample_Apps/tree/master/Paytm_All_in_One

You can create test transactions using the app and get the prod details from PAYTM

**Comment by mrdishant** [comment]
@faisalmushtaq007 Plugin updated now you can use test credentials. (Only on Android)

**Comment by faisalmushtaq007** [comment]
Thanks alot brother
@mrdishant
